### ISSUE TITLE
Refactor end of loop into after loop

### ISSUE THREAD

**Issue by GrosSacASac** [subversivo58/Emitter#5]
https://github.com/subversivo58/Emitter/blob/master/Emitter.js#L55

> It serves to observe the end of the loop because it is asynchronous ... otherwise, many listeners (callbacks in target reference) would be removed before the end of this loop.

There is a miss-understanding of what is asynchronous. Array `.forEach` runs synchronously so there should be no problem. Please provide proof that I am wrong.

**Comment by subversivo58** [comment]
You're not wrong, I've expressed myself wrong.

I was lost with the use of `.splice ()` inside the loop which redefines the array ... at some point "I made this unfortunate statement" in the translation tool and inserted in a comment in issue #2

I'm not in the current version using `.splice()` because I'm using `.filter()` in the function **"filter"** ... the source snippet of this unfortunate comment remains in the **"iterate"** function although I want to change it soon :

```javascript
const iterate = () => {
    let len = this.listeners[e].length
    while (len--) {
        removeListener(this.listeners[e][len])
    }
    delete this.listeners[e]
}
```

Or adding wildcards (#3) after the loop:

```javascript
// remove all listeners references (callbacks) for this target (by target object)
e !== '*' ? delete this.listeners[e] : this.listeners[e] = []
```
